# Шаг 1: Указываем версию Docker Compose
version: '3'

services:
  # Шаг 2: Определяем сервис для базы данных PostgreSQL
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data

  # Шаг 3: Определяем сервис для веб-сервера на основе образа NGINX
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - db

volumes:
  db_data:
