apiVersion: v1
kind: Pod
metadata:
  name: pod-with-pvc
spec:
  containers:
  - name: busybox
    image: busybox
    command: [ "sh", "-c", "echo 'Hello from Kubernetes' > /mnt/storage/test.txt && cat /mnt/storage/test.txt && sleep 3600" ]
    volumeMounts:
    - mountPath: "/mnt/storage"
      name: my-storage
  volumes:
  - name: my-storage
    persistentVolumeClaim:
      claimName: my-pvc
